### ISSUE TITLE
Suggestions to update HD-BM

### ISSUE THREAD

**Issue by Joeycho** [NeuroAI-HD/HD-BM#4]
Hi Tassilo,

I'm Joey who recently joined Philipp's group as a PhD student.

I started to use HD-BM to evaluate it on other public datasets, had some issues with HD-BM and came up with the following suggestions:

1) Add PyTorch reinstallation guide, similar as nnUNet, but with the specific version (?) of PyTorch.

`Error: no valid convolution algorithms available in CuDNN`
In my case I solved this by running: `conda install pytorch==1.10.2 pytorch-cuda=12 -c pytorch -c nvidia`

2) Python version upgrade is required (3.6 -> 3.9 (or newer)). I confronted some package issues (scikit-build, and SimpleITK).
scikit-build (0.17.6) SimpleITK (2.3.1) could not be installed with Python 3.6. They were necessary to resolve the following issue:

https://github.com/MIC-DKFZ/HD-BET/issues/25

3) Maybe add description about the predicted labels in ReadME file (Label 1: NEE, Label 2: CE)

4) Probably include evaluate_folder function as well, if the ground truth files are available. What I did was 1) convert plans.pkl -> plans.json file 2) use nnUNetV2 evaludate_folder function. Do you think.. dataset and plan json files are still necessary if user only has prediction and ground truth segmentation files? 

I will be happy to make PR if that sounds better for you.

**Comment by TaWald** [comment]
Hey Joey,

thanks for posting this issue.

>Add PyTorch reinstallation guide, similar as nnUNet, but with the specific version (?) of PyTorch.

I remember that the installation worked out-of-the-box 2 years ago, but I will check in again if it runs through with newer python versions and the newer Scikit and SimpleITK versions.

Not quite sure why you got the `pytorch` error, as by now torch comes with pre-compiled CuDNN and shouldn't have to be installed with conda.

> ReadME file (Label 1: NEE, Label 2: CE)

Sure, I will include it.

> Evaluate Folder

I will add this function call to the current ones. As you probably notices the nnU-Net only provides case-wise DICE values, which is why I used my own inferencing script, to included metastasis-wise instances, but if you are interested in the default nnU-Net eval it's an easy include.

**Comment by Joeycho** [comment]
Thanks for your response, Tassilo.

I see.. if I remember correctly, pip install (current way) tried to install pytorch 1.10.2 cpu version (without Cuda), and I got the mentioned error.

Sure, if you already have a plan to include your own script, I prefer to wait. No problem.

**Comment by TaWald** [comment]
>Sure, if you already have a plan to include your own script, I prefer to wait. No problem.

I currently do not intend to include the instance eval script, I rather would include the nnU-Net evaluation of semantic segmentation for convenience. Creating instances from segmentations is something I much rather not have in this repository. It will be it's own repository at some time.

**Comment by TaWald** [comment]
I added a few more entrypoints that allow you to predict and evaluate in one go. So in case you want to test that out it would be awesome.

Also I could not reproduce the torch issue for any python version.
I tested py3.6 up till py3.12. The only issue I encountered was SimpleITK versioning which I hope should be fixed with the dependencies I added to the setup.py

**Comment by Joeycho** [comment]
@TaWald 

Thanks for the update, Tassilo. I checked the setup.py and it looks good to me.
